### PR TITLE
Fix DI Extension class deprecation with Symfony 7.1

### PR DESCRIPTION
**Pull request by norkunas**
The "Symfony\Component\HttpKernel\DependencyInjection\Extension" class is considered internal since Symfony 7.1, to be deprecated in 8.1; use Symfony\Component\DependencyInjection\Extension\Extension instead. It may change without further notice. You should not use it from "Presta\SitemapBundle\DependencyInjection\PrestaSitemapExtension".

### CODE REVIEW

**Comment by yann-eugone** [comment]
I've fixed PhpStan in https://github.com/prestaconcept/PrestaSitemapBundle/pull/345

**Comment by yann-eugone** [comment]
Found the PR where that class was deprecated https://github.com/symfony/symfony/pull/53801
Looks like a "side effect", but still need to change the parent

**Review by yann-eugone — APPROVED** [review]

**Comment by yann-eugone** [comment]
Thank you @norkunas :pray:

**Comment by mboron83** [comment]
Hi. @yann-eugone, tell me - when are You going to publish next stable release with this change.

**Comment by yann-eugone** [comment]
Hello @mboron83 

Just did https://github.com/prestaconcept/PrestaSitemapBundle/releases/tag/v4.1.2

**Pull request merged**
