### PR TITLE
Fix PHPCS

### PR DESCRIPTION
**Pull request by yann-eugone**

### CODE REVIEW

**Comment by Koc** [comment]
imho better integrate styleci with `preset: symfony`

**Comment by yann-eugone** [comment]
@Koc can you explain, i don't get it

**Comment by Koc** [comment]
there is a service https://styleci.io/ which integrates with github like travis-ci and check CS of the PRs/commits. Also possible reformat current codebase.

**Comment by yann-eugone** [comment]
@Koc ok, a dedicated issue / PR should be opened for this if you see how to deal with it

**Pull request merged**
