### PR TITLE
Avoid implementing deprecated interface

### PR DESCRIPTION
**Pull request by norkunas**

### CODE REVIEW

**Comment by norkunas** [comment]
:heavy_check_mark:

**Comment by norkunas** [comment]
ping @yann-eugone

**Comment by yann-eugone** [comment]
Sorry for being late, I did not had much time to work on OS last year

I'm not sure if this require a major version
I understand that the message handling will still work 
But I believe that if someone has developed a toolkit around message handlers having that interface, the toolkit won't work anymore
We can say it's very niche, but still, to me it is BC

**Review by yann-eugone — APPROVED** [review]

**Comment by norkunas** [comment]
Thanks for merging

**Pull request merged**
