### PR TITLE
Updated Travis matrix for PHP 7.3 + Symfony 4.2

### PR DESCRIPTION
**Pull request by yann-eugone**
Allowed testing of PHP 7.3 With Symfony 4.2 in testing matrix and fixed tests.

As said in #175 this fix some compatibility issues with newer versions

### CODE REVIEW

**Comment by ostrolucky** [comment]
@yann-eugone want some help here?

**Comment by yann-eugone** [comment]
@ostrolucky yes please. Sorry for that huge delay, but I'm not very availabe for OSS these days.

TBH I have no hint of what is the problem in this one

**Comment by ostrolucky** [comment]
So this is because of deprecations. Merging https://github.com/prestaconcept/PrestaSitemapBundle/pull/177 would be one small step towards solving this

**Comment by yann-eugone** [comment]
Done in #184

**Pull request closed without merging**
