### PR TITLE
Fix deprecated routing config options

### PR DESCRIPTION
**Pull request by xaben**
Fixes deprecation messages for Symfony 2.7.

This bumps the minimum symfony version to 2.2, as pattern was replaced by path since 2.2

### CODE REVIEW

**Comment by xaben** [comment]
@BenoitLeveque Can you please review this PR? Thanks!

**Comment by yann-eugone** [comment]
Not so easy.
You just can't remove 2.1 support on the master branch.
We must choose wisely the way to handle the 2.7 deprecation...

I recommand creating a dedicated branch for the 2.1 to 2.6 version.

**Comment by xaben** [comment]
Well considering Symfony 2.1 support ended in November 2013 and you plan to continue using it, then yeah tagging a release that supports 2.1 or splitting into a different branch is the way to go.

**Comment by Koc** [comment]
+1 for dropping Symfony 2.1 support

**Comment by DZunke** [comment]
+1 bumping minimum version. at a minimum the master should be set to the actual LTS-Version of Symfony2. So the best would be 2.3 (2017) or 2.7 (2019)

http://symfony.com/roadmap#checker

**Comment by chteuchteu** [comment]
+1 for dropping 2.1 support. Plus,

 > The "pattern" option is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.

**Comment by Koc** [comment]
@yann-eugone this PR replaced by #93 and can be closed

**Pull request closed without merging**
