### PR TITLE
Symfony 4 support

### PR DESCRIPTION
**Pull request by istvancsabakis**
#SymfonyConHackday2017

### CODE REVIEW

**Comment by yann-eugone** [comment]
@istvancsabakis did you planned to fix this PR or not ?

**Comment by istvancsabakis** [comment]
yes, but the question is: 
1. leave this bundle services private - this will be a BC for symfony 2,3 users and rewrite unit tests using DI.
2. Make presta services public in symfony 4+

**Comment by yann-eugone** [comment]
We were thinking about it a while ago.

This initiative is pushing us to it : [next major version](https://github.com/prestaconcept/PrestaSitemapBundle/issues/146).

I will update the issue to add this on the roadmap.

**Comment by yann-eugone** [comment]
Closing in favor of #150

**Pull request closed without merging**
