### PR TITLE
Add example of YAML configuration

### PR DESCRIPTION
**Pull request by bocharsky-bw**

### CODE REVIEW

**Comment by yann-eugone** [comment]
I think that we also could add support for XML and more complicated value than `true` or `false`.
I will push as comment some examples

**Comment by yann-eugone** [comment]
```yml
yml_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    options:
        sitemap: true
```

```yml
yml_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    options:
        sitemap:
            section: yml
```

```xml
<route id="xml_homepage" path="/">
    <default key="_controller">AppBundle:Default:index</default>
    <option key="sitemap">true</option>
</route>
```

```xml
<route id="xml_homepage" path="/">
    <default key="_controller">AppBundle:Default:index</default>
    <option key="sitemap">
        {"section":"xml"}
    </option>
</route>
```

**Comment by bocharsky-bw** [comment]
@yann-eugone Hey, thanks for this examples! I've added simple YAML and XML examples of route configuration here in this PR. Maybe expanded configuration examples better move to the separate docs page instead of README? What do you think?

**Comment by yann-eugone** [comment]
@bocharsky-bw yes, I agree with this. i will do it later, can you open an issue ?

**Comment by bocharsky-bw** [comment]
@yann-eugone I did!

**Pull request merged**
